import '@/assets/styles/globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Eset test',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main id="main" className="pb-16 pt-28 px-5 max-w-2xl mx-auto">
          {children}
        </main>
      </body>
    </html>
  )
}
